nosql/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    url(r'^search/', views.show_search_form, name='show-form'),
    url(r'^save-form/', views.save_form, name='save-form'),
    url(r'^filter-results/(?P<datamodels>.*)/(?P<languages>.*)/(?P<movements>.*)/(?P<page>\d+)', views.filter_results, name='filter-results'),
    
    url(r'^(?P<uri>[-\w%]+)/$', views.nosql_detail, name='nosql_detail'),

    url(r'^api/similar/datamodel', views.get_similar_by_datamodel),
    url(r'^api/similar/stackoverflow', views.get_similar_by_stackoverflow_tags),
    url(r'^api/similar/language', views.get_similar_by_language),
    url(r'^api/similar/performance', views.get_similar_by_performance),

    url(r'^api/repositories-by-language', views.get_repositories_progressbars),
    url(r'^api/sentiments', views.get_sentiment_pie),
    url(r'^api/interest-over-time', views.get_interest_over_time),
    url(r'^api/popularity', views.get_popularity),

    url(r'^api/datamodel/(?P<name>.*)', views.get_nosqls_by_datamodel, name='search_by_datamodel'),

    url(r'^api/languages-repos', views.RepositoriesByLanguageData.as_view()),

]

nosqlEngine/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

from nosql import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^nosql/', include('nosql.urls', namespace='nosql')),
    url(r'', views.get_index, name='index'),
]

nosql/forms.py
from django import forms


class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	comments = forms.CharField(required=False,
								widget=forms.Textarea)

nosql/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.template.loader import render_to_string

from .models import NoSQL, DataModel, Movement
from .forms import EmailPostForm
from .services.ranking import SiteStats
from .services.bulletChartsQueries import  BulletStats
from .services import utils
from . import api

from rest_framework.views import APIView
from rest_framework.response import Response

import csv


def get_index(request):
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = '{} ({}) send you a message related to the NoSQLFinder project'.format(cd['name'], 
                cd['email'])
            message = '{}'.format(cd['comments'])
            send_mail(subject, message, '<<SENDER_EMAIL>>', ['<<SENDER_EMAIL>>'])
            sent = True
            form = EmailPostForm()
    else:
        form = EmailPostForm()
    return render(request, 'index.html', {'form': form, 'sent': sent})

    

def show_search_form(request):
    return render(request, 'formWizard.html', {})

def save_form(request):
    datamodels_names = request.POST.getlist('datamodel')
    languages_names = request.POST.getlist('language')
    movements_names = request.POST.getlist('movement')

    datamodels = '+'.join(datamodels_names)
    languages = '+'.join(languages_names)
    movements = '+'.join(movements_names)

    return HttpResponseRedirect(reverse('nosql:filter-results',
                                        args=(datamodels,
                                              languages,
                                              movements, 0)))


def filter_results(request, datamodels, languages, movements, page=0):
    if not api.is_database_empty():
        datamodels_uris = datamodels.split('+')
        languages_uris = languages.split('+')
        movements_names = movements.split('+')

        datamodels = api.get_datamodel_count()
        max_sames = api.get_max_nosql_count_sames()
        views_by_datamodels = api.get_sentiments_by_datamodel()

        homepage_filter = api.HomepageFilter()
        results = homepage_filter.filter(movements_names, datamodels_uris, languages_uris)

        total = len(results)
        context = {}
        page = request.GET.get('page', 1)
        paginator = Paginator(results, 9)

        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)

        context['page'] = page
        context['results'] = results
        context['datamodels'] = datamodels
        context['total'] = total
        context['max_sames'] = max_sames
        context['views_by_datamodels'] = views_by_datamodels

        if not results:
            similar_languages = homepage_filter.filter_by_similar_languages(movements_names, datamodels_uris, languages_uris)
            datamodels_and_licenses = homepage_filter.filter_by_datamodels_and_licenses(movements_names, datamodels_uris)
            best_performance = homepage_filter.filter_by_best_performance()
            context['similar_languages'] = similar_languages
            context['datamodels_and_licenses'] = datamodels_and_licenses
            context['best_performance'] = best_performance

            return render(request, 'recommendations.html', context)

        return render(request, 'grid.html', context)
    else:
        return render(request, 'offline.html', {})


def nosql_detail(request, uri):
    nosql = NoSQL.nodes.get(uri=uri)
    context = {}

    context['nosql'] = nosql
    context['homepages'] = api.get_homepage(nosql.uri)
    context['latest_release'] = api.get_latest_release(nosql.uri)
    context['status'] = api.get_status(nosql.uri)
    context['frequently_updated'] = api.get_frequently_updated(nosql.uri)
    context['documentation'] = api.get_documentation(nosql.uri)

    site_stats = SiteStats()

    ## Data for the bullet charts

    bullet_stats = BulletStats()
    stackoverflow_bullet_data = bullet_stats.get_stackoverflow_views(nosql.uri)
    context['stackoverflow_bullet_data'] = stackoverflow_bullet_data

    github_bullet_data = bullet_stats.get_repository_stars(nosql.uri)
    context['github_bullet_data'] = github_bullet_data

    stackshare_bullet_data = bullet_stats.get_stackshare_votes(nosql.uri)
    context['stackshare_bullet_data'] = stackshare_bullet_data

    alternativeto_bullet_data = bullet_stats.get_alternativeto_likes(nosql.uri)
    context['alternativeto_bullet_data'] = alternativeto_bullet_data

    dbengine_bullet_data = bullet_stats.get_dbengine_score(uri)
    context['dbengine_bullet_data'] = dbengine_bullet_data
    
    github_ranking = site_stats.get_repositories_ranking(5)
    context['github_ranking'] = github_ranking

    stackshare_ranking = site_stats.get_stackshare_ranking(nosql.name)
    context['stackshare_ranking'] = stackshare_ranking

    alternativeto_ranking = site_stats.get_alternativeto_ranking(nosql.name)
    context['alternativeto_ranking'] = alternativeto_ranking

    github_position = site_stats.get_position_in_repositories_ranking(nosql.name)
    context['github_position'] = github_position

    stackshare_position = site_stats.get_position_in_stackshare_ranking(nosql.name)
    context['stackshare_position'] = stackshare_position

    alternativeto_position = site_stats.get_position_in_alternativeto_ranking(nosql.name)
    context['alternativeto_position'] = alternativeto_position

    context['datamodels'] = api.get_datamodels(nosql.uri)
    context['summary'] = api.get_summary(nosql.uri)
    context['developed_languages'] = api.get_developed_languages(nosql.uri)
    context['supported_datatypes'] = api.get_supported_datatypes(nosql.uri)
    context['nosql_rating'] = api.get_performance_rating(nosql.uri)

    stackoverflow_tag = api.get_stackoverflow_tag(nosql.uri)
    context['stackoverflow_tag'] = stackoverflow_tag

    context['stackoverflow_unanswered'] = api.get_percent_unanswered_questions(nosql.uri)

    alternativeto_post = api.get_alternativeto_post(nosql.uri)
    context['alternativeto_post'] = alternativeto_post

    stackshare_post = api.get_stackshare_post(nosql.uri)
    context['stackshare_post'] = stackshare_post
    context['stackshare_comments'] = api.get_stackshare_comments(nosql.uri)

    dbengine_post = api.get_dbengine_post(nosql.uri)
    context['dbengine_post'] = dbengine_post

    repository = api.get_repository(nosql.uri)
    context['repository'] = repository

    wikipedia_post = api.get_wikipedia_post(nosql.uri)
    context['wikipedia_post'] = wikipedia_post

    developers = api.get_developers(nosql.uri)
    context['developers'] = developers

    operating_systems = api.get_operating_systems(nosql.uri)
    context['operating_systems'] = operating_systems

    uses = api.get_uses(nosql.uri)
    context['uses'] = uses

    apis = api.get_apis(nosql.uri)
    context['apis'] = apis

    transactions = api.get_transaction_methods(nosql.uri)
    context['transactions'] = transactions

    consistencies = api.get_consistency_methods(nosql.uri)
    context['consistencies'] = consistencies

    repositories_by_language = api.get_repositories_by_language(nosql.uri)
    context['repositories_by_language'] = repositories_by_language

    technologies = api.get_supported_technologies(nosql.uri)
    context['technologies'] = technologies

    tools = api.get_supported_tools(nosql.uri)
    context['tools'] = tools

    context['drivers'] = api.get_drivers(nosql.uri)

    drivers_repos = api.get_drivers_repositories(nosql.uri)
    context['drivers_repos'] = drivers_repos

    clients = api.get_clients(nosql.uri)
    context['clients'] = clients

    links = api.get_links(nosql.uri)
    context['links'] = links

    alternativeto_recommendations = api.get_alternativeto_recommendations(nosql.uri)
    context['alternativeto_recommendations'] = alternativeto_recommendations

    context['associated_tags'] = api.get_associated_tags(nosql.uri)

    context['shared_tags'] = api.get_shared_tags(nosql.uri)

    interest_over_time = api.get_interest_over_time(nosql.uri)
    context['interest_over_time'] = interest_over_time
    context['is_valid_interest_over_time'] = any(item['queries'] > 0 for item in interest_over_time) and len(interest_over_time) > 0

    context['comments'] = api.get_comments(nosql.uri)
    context['comments_text'] = api.get_comments_text(nosql.uri)

    comments_percents = api.get_percents_comments(nosql.uri)
    context['comments_percents'] = comments_percents
    context['has_comments_percents'] = any(comments_percents[k] > 0 for k in comments_percents.keys()) and len(comments_percents) > 0

    context['comments_points'] = api.get_comments_points(nosql.uri)

    popular_apis = api.get_all_popular_apis()
    context['popular_apis'] = popular_apis

    popular_transactions = api.get_all_popular_transactions_methods()
    context['popular_transactions'] = popular_transactions

    popular_consistencies = api.get_all_popular_consistency_methods()
    context['popular_consistencies'] = popular_consistencies

    context['all_transactions'] = set(transactions + popular_transactions)
    context['all_apis'] = set(popular_apis + apis)
    context['all_consistencies'] = set(consistencies + popular_consistencies)

    all_stackoverflow_views = api.get_all_stackoverflow_views()
    context['all_stackoverflow_views'] = all_stackoverflow_views
    context['has_stackoverflow_views'] = any(item['name'] == nosql.name for item in all_stackoverflow_views)
    
    all_repositories_stars = api.get_all_repositories_stars()

nosql/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block title %} {% endblock %}</title>


		<!--[if lt IE 10]>
		      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		      <![endif]-->

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />


		<!-- font -->
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,800" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Russo+One" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Meera+Inimai" rel="stylesheet">

		<!-- bootstrap -->
		<link href="{% static "vendor/bootstrap/bootstrap.min.css" %}" rel="stylesheet" type="text/css" >

		<!-- icons -->
		<!-- <link href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css" rel="stylesheet" type="text/css"> -->
		<link href="{% static "assets/fonts/themify-icons/themify-icons.css" %}" rel="stylesheet" type="text/css">

		<!-- <link href="https://allyoucan.cloud/cdn/icofont/1.0.0beta/css/icofont.css" rel="stylesheet" type="text/css"> -->
		<link href="{% static "assets/fonts/icofont/icofont.min.css"%}" rel="stylesheet" type="text/css">

		<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet" type="text/css"> -->
		<link href="{% static "assets/fonts/simple-line-icons-master/css/simple-line-icons.css"%}" rel="stylesheet" type="text/css">

		<!-- <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css"> -->
		<link href="{% static "assets/fonts/ionicons/css/ionicons.min.css"%}" rel="stylesheet" type="text/css">

		<!-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
		<link href="{% static "assets/fonts/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

		<!-- rating plugin -->
		<link href="{% static "vendor/jquery-barrating/fontawesome-stars.css" %}" rel="stylesheet" type="text/css">
		<link href="{% static "vendor/jquery-barrating/fontawesome-stars-o.css" %}" rel="stylesheet" type="text/css">

		<!-- data tables -->
		<link href="{% static "vendor/datatables/dataTables.bootstrap4.min.css" %}" rel="stylesheet" type="text/css">
		<link href="{% static "vendor/datatables/responsive.bootstrap4.min.css" %}" rel="stylesheet" type="text/css">

		<link href="{% static "vendor/datatables/buttons.dataTables.min.css" %}" rel="stylesheet" type="text/css">

		<!-- Owl carousel -->
		<link rel="stylesheet" type="text/css" href="{% static "vendor/owl-carousel/owl.theme.default.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "vendor/owl-carousel/owl.carousel.css" %}">

		<link href="{% static "assets/app/css/style.css" %}" rel="stylesheet" type="text/css">
		<link href="{% static "assets/app/css/jquery.mCustomScrollbar.css" %}" rel="stylesheet" type="text/css">


		<!-- theme for this page -->
		{% block styles %}
		{% endblock%}
	</head>
	<body>

		<!-- <div class="theme-loader">
			<div class="loader-block">
				<svg id="loader2" viewBox="0 0 100 100">
					<circle id="circle-loader2" cx="50" cy="50" r="45"></circle>
				</svg>
			</div>
		</div> -->

		<div id="pcoded" class="pcoded">
			<div class="pcoded-overlay-box"></div>
			<div class="pcoded-container navbar-wrapper">

				<!-- navbar -->
				{% include "navbar.html" %}

				<!-- Main Content -->
				<div class="pcoded-main-container">
					{% block content %}
					{% endblock %}
				</div>

			</div>
		</div>


		<script type="text/javascript" src="{% static "vendor/jquery/jquery.min.js" %}"></script>
		<script type="text/javascript" src="{% static "vendor/jquery-ui/jquery-ui.min.js" %}"></script>
		<script type="text/javascript" src="{% static "vendor/popper/popper.min.js" %}"></script>
		<script type="text/javascript" src="{% static "vendor/bootstrap/bootstrap.min.js" %}"></script>

		<script type="text/javascript" src="{% static "vendor/jquery-slimscroll/jquery.slimscroll.js" %}"></script>

		<script type="text/javascript" src="{% static "vendor/modernizr/modernizr.js" %}"></script>
		<script type="text/javascript" src="{% static "vendor/modernizr/css-scrollbars.js" %}"></script>

		<script src="{% static "vendor/isotope/jquery.isotope.js" %}"></script>
		<script src="{% static "vendor/isotope/isotope.pkgd.min.js" %}"></script>

		<!-- rating -->
		<script src="{% static "vendor/jquery-barrating/jquery.barrating.js" %}" type="text/javascript"></script>

		<!-- chartjs -->
		<script type="text/javascript" src="{% static "vendor/chartjs/moment.min.js" %}"></script>
		<script src="{% static "vendor/chartjs/Chart.js" %}"></script>

		<script src="{% static "assets/app/js/pcoded.min.js" %}"></script>
		<script src="{% static "assets/app/js/demo-12.js" %}"></script>
		<script src="{% static "assets/app/js/jquery.mCustomScrollbar.concat.min.js" %}"></script>

		{% block scripts %}
		{% endblock %}

		<script type="text/javascript">
			 // tooltips
		    $(document).ready(function() {
		        $('[data-toggle="tooltip"]').tooltip();
		    });

		    // rating
		    $(document).ready(function() {
		    	ratings = $('[data-toggle="rating"]');
				for(i=0; i < ratings.length; i++){
					currentRating = $(ratings[i]).data('current-rating');
					$(ratings[i]).barrating({
						theme: 'fontawesome-stars-o',
						initialRating: currentRating
					});
					$(ratings[i]).barrating('readonly', true);
				}

				$("#name-search").bind('click', function(){
					text = $("name-search-input").val();
					console.log(text);
  					// var href = "/nosql/api/search/" + text;
  					// window.location = href;
				});
				// function searchNosqlName(event) {
  		// 			event.preventDefault();
  		// 			text = $("name-search-input").val();
  		// 			var href = "/nosql/api/search/" + text;
  		// 			window.location = href;
				// }
		    });
		</script>
	</body>
</html>

nosql/templates/comparisonByLanguageTable.html
{% load staticfiles %}
<div class="dt-responsive table-responsive">
	<table id="compare-table" data-toggle="data-table" class="table table-bordered nowrap">
		<thead>
			<tr>
				<th>
					<span class="text-muted">Name</span>
				</th>
				<th>
					<span class="text-muted">Popularity</span>
				</th>
				<th>
					<span class="text-muted">Performance</span>
				</th>
				<th>
					<span class="text-muted"># Langs</span>
				</th>
				<th>
					<span class="text-muted">Languages</span>
				</th>
			</tr>
		</thead>
		<tbody>
			{% for similar in similars %}
			<tr>
				<td>{{ similar.name }}</td>
				<td class="text-center">
					<canvas data-toggle="sparkline" width="146" height="41" data-interest="{% for i in similar.interest_over_time %}{{ i.num_queries }}{% if not forloop.last %},{% endif %}{% endfor %}" data-years="{% for i in similar.interest_over_time %}{{ i.year }}{% if not forllop.last %},{% endif %}{% endfor %}"></canvas>
				</td>
				<td data-order="{{ similar.sentiment }}" data-toggle="tooltip" title="{{ similar.rating }}">
					<select name="rating" data-toggle="rating" data-current-rating="{{ similar.rating }}" autocomplete="off">
						<option value="" label="0"></option>
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
					</select>
				</td>
				<td data-order="{{ similar.number_languages }}">{{ similar.number_languages }}</td>
				<td data-order="{{ similar.number_languages }}">
					<div class="m-b-5">
					{% for lang in similar.languages %}
						<span class="label label-cyan m-b-5 p-r-5 p-l-5">
							{{ lang }}
						</span>
						{% if forloop.counter|divisibleby:6 %}
						</div>
						<div class="m-b-5">
						{% endif %}
					{% endfor %}
					</div>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

nosql/templates/comparisonTable.html
<div class="dt-responsive table-responsive">
	<table id="compare-table" data-toggle="data-table" class="table table-bordered nowrap">
		<thead>
			<tr>
				<th>
					<span class="text-muted">Name</span>
				</th>
				<th>
					<i class="ti-stack-overflow f-30 text-muted"></i>
				</th>
				<th>
					<i class="fa fa-github f-30 text-muted"></i>
				</th>
				<th>
					<i class="ti-sharethis-alt f-25 text-muted"></i>
				</th>
				<th>
					<span class="dbengine-title text-muted f-25" style="line-height: 1;">
					DB
					</span>
				</th>
				<th>
					<span class="text-muted f-30" style="line-height: 1;">
					a
					</span>
				</th>
				<th>
					<span class="text-muted">
					Popularity
					</span>
				</th>
				<th>
					<span class="text-muted">
					Performance
					</span>
				</th>
			</tr>
		</thead>
		<tbody>
			{% for similar in similars %}
			<tr>
				<td>{{ similar.name }}</td>
				<td data-order="{{ similar.stackoverflow }}">{{ similar.stackoverflow }}</td>
				<td data-order="{{ similar.repositories }}">{{ similar.repositories }}</td>
				<td data-order="{{ similar.stackshare_votes }}">{{ similar.stackshare_votes }}</td>
				<td data-order="{{ simiar.dbengine_rank }}">{{ similar.dbengine_rank }}</td>
				<td data-order="{{ similar.alternativeto }}">{{ similar.alternativeto_likes }}</td>
				<td class="text-center">
					<canvas data-toggle="sparkline" width="146" height="41" data-interest="{% for i in similar.interest_over_time %}{{ i.num_queries }}{% if not forloop.last %},{% endif %}{% endfor %}" data-years="{% for i in similar.interest_over_time %}{{ i.year }}{% if not forllop.last %},{% endif %}{% endfor %}"></canvas>
				</td>
				<td data-order="{{ similar.sentiment }}" data-toggle="tooltip" title="{{ similar.rating }}">
					<select name="rating" data-toggle="rating" data-current-rating="{{ similar.rating }}" autocomplete="off">
						<option value="" label="0"></option>
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
					</select>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

nosql/templates/popularityChart.html
<div class="row">
	<div class="col-sm-6 b-r-default text-center">
  		<div>
    		<i class="round-icon fa fa-stack-overflow f-20 m-b-10 stackoverflow" data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Stack Overflow"></i>
  		</div>
  		<div>
			<h5 class="f-w-600 m-b-5">
			{% if number_questions %}{{ number_questions }}{% endif %}
			</h5>
  		</div>
    	<small class="text-muted f-w-600">Questions</small>
		<div class="progress m-t-5" style="height: 8px;">
			<div class="progress-bar bg-c-green" role="progressbar" aria-valuemin="0" aria-valuemax="100" data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Answered: {{ percentage_answered }}%" style="width:{{ percentage_answered  }}%">
			</div>
			<div class="progress-bar bg-c-danger" role="progressbar" aria-valuemin="0" aria-valuemax="100" data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Unanswered: {{ percentage_unanswered }}%" style="width:{{ percentage_unanswered  }}%;background-color: #ff728f;">
			</div>
		</div>
	</div>
	<div class="col-sm-6 text-center">
  		<div>
  			<i class="round-icon fa fa-github-alt document f-20 m-b-10"  data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Github"></i>
  		</div>
  		<div>
    		<h5 class="f-w-600">{{ github_stars }}</h5>
    	</div>
		<small class="text-muted f-w-600 m-b-0">Repositories</small>
	</div>
</div>
<hr>
<div class="row p-b-10">
	<small class="text-muted f-w-600" data-toggle="tooltip" data-placement="top" data-trigger="hover" title="Hacker News" style="margin: 0 auto;">
		<i class="fa fa-hacker-news f-20 m-r-10" style="color: #FF9800;"></i>
		Performance Comments
	</small>
</div>
<div class="row">
	{% if comments %}
	<canvas id="comments-chart-{{ uri }}" width="260" height="100" data-years="{% for c in comments %}{{ c.created_at }}{% if not forloop.last %},{% endif %}{% endfor %}" data-sentiment="{% for c in comments %}{{ c.sentiment }}{% if not forloop.last %},{% endif %}{% endfor %}"></canvas>
	{% else %}
	<div class="m-b-10" style="margin: 0 auto;">
		<div class="text-center p-b-5">
			<i class="icofont icofont-growth f-60" style="color: #e6e6e6;"></i>
		</div>
		<small class="text-muted">There's no data for this chart</small>
	</div>
	{% endif %}
</div>
<div class="text-right p-t-10">
	<a href="{% url 'nosql:nosql_detail' uri=uri %}" class="btn btn-cyan waves-effect waves-light btn-sm"> View Info
	</a>
</div>

nosql/templates/repositoriesProgressbars.html
<h6 class="card-section-title">
	Supported Languages
</h6>
{% if languages %}
{% for lang in languages %}
<div class="progress-box">
	<h6 class="text-muted f-12" style="margin-bottom: -3px;">{{ lang.name|title }}</h6>
	<div class="progress d-inline-block" style="width: 100%;">
		<div class="progress-bar {% cycle 'bg-c-blue' 'bg-c-yellow' 'bg-c-green' 'progress-bar-emrald' 'progress-bar-purple' %}" style="width:{{ lang.percentage }}% ">
			<label>{{ lang.percentage }}%</label>
		</div>
	</div>
</div>
{% endfor %}
{% else %}
{% include "emptyData.html" %}
{% endif %}
<hr>
<small class="text-muted">Based on the amount of repositories for every language.</small>
<div class="text-right p-t-10">
						<a href="{% url 'nosql:nosql_detail' uri=uri %}" class="btn btn-cyan waves-effect waves-light btn-sm"> View Info
							</a>
					</div>

nosql/templates/sentimentsPie.html
{% load get_bigger_sentiment %}
<h6 class="card-section-title">
	Performance
</h6>
{% if sentiments.negative > 0 or sentiments.positive > 0  or sentiments.neutral > 0%}
<canvas id="{{ uri }}-performance-chart" width="250", height="100"  data-positive="{{ sentiments.positive }}" data-neutral="{{ sentiments.neutral }}" data-negative="{{ sentiments.negative }}" data-total="{{ sentiments.total }}"></canvas>

<div class="p-t-20" style="display: inline-flex;">
	{% with sentiments|get_bigger_sentiment as final_sentiment %}
 	{% if final_sentiment == 'positive' %}
	<span class="square-icon positive">
		<i class="icofont-laughing"></i>
	</span>
	<span class="text-muted p-t-5 f-12">
		Mostly Positive
	</span>
	{% elif final_sentiment == 'negative' %}
	<span class="square-icon negative">
		<i class="icofont-sad"></i>
	</span>
	<span class="text-muted p-t-5 f-12">
		Mostly Negative
	</span>
	{% else %}
	<span class="square-icon neutral">
		<i class="icofont-expressionless"></i>
	</span>
	<span class="text-muted p-t-5 f-12">
		Mostly Neutral
	</span>
	{% endif %}
	{% endwith %}
</div>
<div class="text-left text-muted p-t-5">
		<small>From <span class="f-w-600" style="color: #36a2eb;">{{ sentiments.total }}</span> comments</small>
</div>
{% else %}
{% include "emptyData.html" %}
{% endif %}
<hr class="m-t-0">
<small class="text-muted">Based on the amount of comments and their performance sentiment</small>
<div class="text-right p-t-10">
						<a href="{% url 'nosql:nosql_detail' uri=uri %}" class="btn btn-cyan waves-effect waves-light btn-sm"> View Info
							</a>
					</div>